USE [CHUNGKHOAN]
GO

/****** Object:  Trigger [dbo].[TRIGGER_LENHKHOP]    Script Date: 03/05/2022 11:18:15 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[TRIGGER_LENHKHOP]
ON [dbo].[LENHKHOP] 
AFTER INSERT
AS
DECLARE @MACP NVARCHAR(7)
BEGIN
		SET @MACP = (SELECT a.MaCP FROM LENHDAT a, inserted b WHERE a.ID = b.IDLENHDAT)

		UPDATE dbo.BangGiaTrucTuyen 
		SET GiaKhop = (SELECT GIAKHOP FROM inserted),
			SoLuongKhop = (SELECT SOLUONGKHOP FROM inserted),
			TongSo = (TongSo + (SELECT SOLUONGKHOP FROM inserted))
		WHERE dbo.BangGiaTrucTuyen.MaCP = @MACP
END
GO

ALTER TABLE [dbo].[LENHKHOP] ENABLE TRIGGER [TRIGGER_LENHKHOP]
GO

